name: Bug Report
description: Report something that isn't working correctly
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting! Please fill in as much detail as you can.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Open Koe
        2. Press ⌥Space
        3. ...

  - type: input
    id: macos-version
    attributes:
      label: macOS version
      placeholder: e.g. 15.2 (Sequoia)
    validations:
      required: true

  - type: input
    id: koe-version
    attributes:
      label: Koe version
      placeholder: e.g. 0.1.2 (check tray menu)
    validations:
      required: true

  - type: dropdown
    id: recognition-mode
    attributes:
      label: Recognition mode
      options:
        - On-Device
        - Cloud
        - Not sure
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste any relevant error messages or attach screenshots.
