name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Have an idea? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the pain point or use case.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you thought about?
